package Game;

public enum Places {
    ABANDONED_CABIN,
    SUPER_DUPER_MART,
    RED_ROCKET,
    ABANDONED_BUILDING,
    ABANDONED_FACTORY,
    ATOMATOYS_WAREHOUSE,
    BLAMCO_FACTORY,
    CORVEGA_FACTORY,
    HOLY_HEART_HOSPITAL,
    LAKEVILLE_LIBRARY,
    MACHINE_PARTS_FACTORY,
    MASS_CHEMICAL_BUILDING,
    NUKA_COLA_PLANT,
    OFFICE_BUILDING,
    OLD_CANDY_FACTORY,
    OLD_WAREHOUSE,
    RAIDER_CAMP,
    ROBCO_PLANT,
    RUINED_LIBRARY;
}
